# Generated by Django 5.2.7 on 2025-10-30 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('icon', models.CharField(default='fa-info', max_length=50)),
                ('color', models.CharField(default='blue', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('party_photo', models.ImageField(blank=True, null=True, upload_to='parties/')),
                ('status', models.CharField(default='Running', max_length=20)),
                ('status_color', models.CharField(default='blue', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_name', models.CharField(default='Admin User', max_length=100)),
                ('admin_role', models.CharField(default='Administrator', max_length=100)),
                ('admin_avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('status', models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=20)),
                ('major_minor', models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor')], max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('dept_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='voters/')),
                ('has_voted', models.BooleanField(default=False)),
            ],
        ),
    ]
